matches:
  - trigger: ":esn"
    replace: "ñ"
  - trigger: ":esN"
    replace: "Ñ"
  - trigger: ":esa"
    replace: "á"
  - trigger: ":ese"
    replace: "é"
  - trigger: ":esi"
    replace: "í"
  - trigger: ":eso"
    replace: "ó"
  - trigger: ":esu"
    replace: "ú"
  - trigger: ":esA"
    replace: "Á"
  - trigger: ":esE"
    replace: "É"
  - trigger: ":esI"
    replace: "Í"
  - trigger: ":esO"
    replace: "Ó"
  - trigger: ":esU"
    replace: "Ú"
